package narrator

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// Analyzer is the narrow interface the narrator uses to call an LLM.
// internal/llm.Client satisfies this shape, and tests can mock it without
// bringing the http client or provider config into the test file.
type Analyzer interface {
	IsEnabled() bool
	Analyze(systemPrompt, userPrompt string) (*AnalyzerResponse, error)
}

// AnalyzerResponse mirrors internal/llm.Response. Re-declared here so
// narrator does not import internal/llm. The adapter below converts.
type AnalyzerResponse struct {
	Content    string
	Model      string
	TokensUsed int
}

// Postmortem is the enriched output of an LLM-assisted incident write-up.
// The four prose fields are free-form; TLDR is one sentence.
type Postmortem struct {
	IncidentID       string        `json:"incident_id"`
	TLDR             string        `json:"tldr"`
	ExecutiveSummary string        `json:"executive_summary"`
	WhatHappened     string        `json:"what_happened"`
	WhyItHappened    string        `json:"why_it_happened"`
	HowItWasFixed    string        `json:"how_it_was_fixed"`
	Prevention       []string      `json:"prevention"`
	Confidence       float64       `json:"confidence"`
	GeneratedBy      string        `json:"generated_by"` // "llm:<provider>:<model>" or "deterministic"
	TokensUsed       int           `json:"tokens_used,omitempty"`
	Latency          time.Duration `json:"latency_ns,omitempty"`
}

// Markdown renders the postmortem as a single Markdown document suitable
// for pasting into Jira, Linear, a blog post, or a GitHub incident issue.
func (p Postmortem) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Postmortem: %s\n\n", firstNonEmpty(p.IncidentID, "incident"))
	if p.TLDR != "" {
		fmt.Fprintf(&b, "**TL;DR.** %s\n\n", strings.TrimSpace(p.TLDR))
	}
	if p.ExecutiveSummary != "" {
		b.WriteString("## Executive summary\n\n")
		b.WriteString(strings.TrimSpace(p.ExecutiveSummary))
		b.WriteString("\n\n")
	}
	if p.WhatHappened != "" {
		b.WriteString("## What happened\n\n")
		b.WriteString(strings.TrimSpace(p.WhatHappened))
		b.WriteString("\n\n")
	}
	if p.WhyItHappened != "" {
		b.WriteString("## Why it happened\n\n")
		b.WriteString(strings.TrimSpace(p.WhyItHappened))
		b.WriteString("\n\n")
	}
	if p.HowItWasFixed != "" {
		b.WriteString("## How it was fixed\n\n")
		b.WriteString(strings.TrimSpace(p.HowItWasFixed))
		b.WriteString("\n\n")
	}
	if len(p.Prevention) > 0 {
		b.WriteString("## Prevention\n\n")
		for _, item := range p.Prevention {
			fmt.Fprintf(&b, "- %s\n", strings.TrimSpace(item))
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "---\n_Generated by %s · confidence %.0f%%_\n", p.GeneratedBy, p.Confidence*100)
	if p.TokensUsed > 0 {
		fmt.Fprintf(&b, "_Tokens used: %d_\n", p.TokensUsed)
	}
	return b.String()
}

// Enrich upgrades a deterministic Verdict into a rich Postmortem by asking
// the Analyzer (typically an LLM) for prose. If the Analyzer is nil, not
// enabled, or returns an error, Enrich falls back to a deterministic
// Postmortem built from the Verdict fields with the same GeneratedBy =
// "deterministic" marker.
//
// Enrich is safe against malformed LLM output: if the response does not
// parse as strict JSON, the function also falls back to deterministic.
func Enrich(ctx context.Context, inc Incident, v Verdict, az Analyzer) Postmortem {
	base := deterministicPostmortem(inc, v)
	if az == nil || !az.IsEnabled() {
		return base
	}

	start := time.Now()
	systemPrompt := systemPromptTemplate
	userPayload, err := json.Marshal(map[string]any{
		"incident":   inc,
		"verdict":    v,
		"request":    "postmortem",
		"style":      "concise, technical, no marketing language",
		"audience":   "senior platform engineers",
	})
	if err != nil {
		return base
	}
	resp, err := az.Analyze(systemPrompt, string(userPayload))
	if err != nil || resp == nil || strings.TrimSpace(resp.Content) == "" {
		return base
	}

	parsed, perr := parseLLMPostmortem(resp.Content)
	if perr != nil {
		// Conservative: if JSON parse fails, keep the deterministic
		// version but note that an LLM attempt was made.
		base.GeneratedBy = "deterministic (llm-response-unparseable)"
		return base
	}
	parsed.IncidentID = firstNonEmpty(parsed.IncidentID, base.IncidentID)
	parsed.Confidence = clampUnit(firstNonZero(parsed.Confidence, v.Confidence))
	parsed.GeneratedBy = fmt.Sprintf("llm:%s", firstNonEmpty(resp.Model, "unknown"))
	parsed.TokensUsed = resp.TokensUsed
	parsed.Latency = time.Since(start)
	return parsed
}

const systemPromptTemplate = `You are Immortal, an autonomous self-healing engine. Produce a postmortem for the incident described in the user payload.

Output format. Return ONLY compact JSON with this exact shape:
{
  "incident_id": "<id>",
  "tldr": "<one sentence, max 25 words>",
  "executive_summary": "<2-3 paragraphs, plain prose, no bullet points>",
  "what_happened": "<timeline prose, 1-2 paragraphs>",
  "why_it_happened": "<cause prose, 1-2 paragraphs>",
  "how_it_was_fixed": "<action prose tied to what the engine actually did>",
  "prevention": ["<suggestion 1>", "<suggestion 2>"]
}

Rules:
- Use only facts from the provided Verdict. Do not invent metrics, services, or actions.
- No marketing language, no hype, no em dashes.
- Prose must be readable by a senior platform engineer. Assume they understand SRE vocabulary.
- TL;DR must fit in one short sentence.
- Prevention is optional; include at most 3 items.
- No text outside the JSON. No markdown code fences.`

// parseLLMPostmortem tolerates leading or trailing prose by locating the
// first { and last } in the string. LLMs sometimes wrap JSON in ```json
// fences despite instructions; we strip those.
func parseLLMPostmortem(raw string) (Postmortem, error) {
	trimmed := strings.TrimSpace(raw)
	// Strip markdown code fence if present.
	trimmed = strings.TrimPrefix(trimmed, "```json")
	trimmed = strings.TrimPrefix(trimmed, "```")
	trimmed = strings.TrimSuffix(trimmed, "```")
	trimmed = strings.TrimSpace(trimmed)
	// Locate the JSON object.
	start := strings.Index(trimmed, "{")
	end := strings.LastIndex(trimmed, "}")
	if start < 0 || end <= start {
		return Postmortem{}, errors.New("no JSON object in LLM response")
	}
	trimmed = trimmed[start : end+1]

	var p Postmortem
	if err := json.Unmarshal([]byte(trimmed), &p); err != nil {
		return Postmortem{}, fmt.Errorf("unmarshal: %w", err)
	}
	return p, nil
}

// deterministicPostmortem fills a Postmortem from Verdict + Incident without
// any LLM. Used when LLM is disabled or fails.
func deterministicPostmortem(inc Incident, v Verdict) Postmortem {
	p := Postmortem{
		IncidentID:       incidentID(inc),
		TLDR:             strings.TrimSuffix(v.Brief(), "."),
		ExecutiveSummary: v.Cause,
		WhatHappened:     (&Narrator{}).Brief(inc),
		WhyItHappened:    v.Cause,
		HowItWasFixed:    strings.Join(v.Action, "; "),
		Prevention:       []string{},
		Confidence:       v.Confidence,
		GeneratedBy:      "deterministic",
	}
	return p
}

func firstNonEmpty(ss ...string) string {
	for _, s := range ss {
		if strings.TrimSpace(s) != "" {
			return s
		}
	}
	return ""
}
func firstNonZero(vs ...float64) float64 {
	for _, v := range vs {
		if v != 0 {
			return v
		}
	}
	return 0
}
func clampUnit(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}
